2023-12-03 23:05:23,111 ERROR Message: 
Stacktrace:
	GetHandleVerifier [0x00007FF784F282B2+55298]
	(No symbol) [0x00007FF784E95E02]
	(No symbol) [0x00007FF784D505AB]
	(No symbol) [0x00007FF784D9175C]
	(No symbol) [0x00007FF784D918DC]
	(No symbol) [0x00007FF784DCCBC7]
	(No symbol) [0x00007FF784DB20EF]
	(No symbol) [0x00007FF784DCAAA4]
	(No symbol) [0x00007FF784DB1E83]
	(No symbol) [0x00007FF784D8670A]
	(No symbol) [0x00007FF784D87964]
	GetHandleVerifier [0x00007FF7852A0AAB+3694587]
	GetHandleVerifier [0x00007FF7852F728E+4048862]
	GetHandleVerifier [0x00007FF7852EF173+4015811]
	GetHandleVerifier [0x00007FF784FC47D6+695590]
	(No symbol) [0x00007FF784EA0CE8]
	(No symbol) [0x00007FF784E9CF34]
	(No symbol) [0x00007FF784E9D062]
	(No symbol) [0x00007FF784E8D3A3]
	BaseThreadInitThunk [0x00007FFB6E9F26AD+29]
	RtlUserThreadStart [0x00007FFB6EC4A9F8+40]


2023-12-03 23:53:01,919 WARNING Connection pool is full, discarding connection: localhost. Connection pool size: 1
2023-12-03 23:53:02,658 WARNING Connection pool is full, discarding connection: localhost. Connection pool size: 1
2023-12-03 23:53:03,804 WARNING Connection pool is full, discarding connection: localhost. Connection pool size: 1
2023-12-03 23:53:06,020 WARNING Connection pool is full, discarding connection: localhost. Connection pool size: 1
2023-12-08 01:09:00,850 ERROR Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2023-12-08 01:09:00,879 ERROR Exception traceback:
Traceback (most recent call last):
  File "D:\GGL_DRV\CODE\lifehacker_bot\venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "D:\GGL_DRV\CODE\lifehacker_bot\venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "D:\GGL_DRV\CODE\lifehacker_bot\venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
  File "D:\GGL_DRV\CODE\lifehacker_bot\venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GGL_DRV\CODE\lifehacker_bot\venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GGL_DRV\CODE\lifehacker_bot\venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GGL_DRV\CODE\lifehacker_bot\venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GGL_DRV\CODE\lifehacker_bot\venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

